site_name: AI Consulting Company
site_description: Professional AI Consulting Services
site_url: https://Vikramardham.github.io/butterflai
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Solutions:
      - solutions/index.md
  - Projects:
      - projects/index.md
  - Blog:
      - blog/index.md
  - Team: team/index.md
  - Testimonials: testimonials.md
  - Contact: contact.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/YourGitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/YourCompany

copyright: Copyright &copy; 2024 AI Consulting Company
