site_name: ButterflAI
site_description: ButterflAI
site_url: https://Vikramardham.github.io/butterflai
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  custom_dir: docs/overrides
  
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Build:
      - Overview: build/index.md
      - Development Environment: build/development-environment/index.md
      - Framework Selection: build/choosing-frameworks/index.md
      - Data Pipeline Best Practices: build/data-pipeline-best-practices/index.md
      - Model Training Strategies: build/model-training-strategies/index.md
      - Topics:
          - Data Preparation: build/topic/data-preparation/index.md
          - Model Architecture: build/topic/model-architecture/index.md
          - Training Techniques: build/topic/training-techniques/index.md
          - Testing & Validation: build/topic/testing-validation/index.md
          - Performance Optimization: build/topic/performance-optimization/index.md
  - Deploy:
      - Overview: deploy/index.md
      - MLOps Fundamentals: deploy/mlops-fundamentals/index.md
      - Containerizing AI Applications: deploy/containerizing-ai-apps/index.md
      - Cloud Deployment Options: deploy/cloud-deployment-options/index.md
      - Monitoring AI Systems: deploy/monitoring-ai-systems/index.md
      - Topics:
          - Infrastructure as Code: deploy/topic/infrastructure-as-code/index.md
          - CI/CD for AI: deploy/topic/cicd-for-ai/index.md
          - Scaling Strategies: deploy/topic/scaling-strategies/index.md
          - Security Best Practices: deploy/topic/security-best-practices/index.md
  - Blog:
      - Overview: blog/index.md
      - LLMs:
          - Getting Started with LLMs: blog/getting-started-with-llms/index.md
          - Advanced Prompt Engineering: blog/advanced-prompt-engineering/index.md
          - Fine-tuning LLMs: blog/fine-tuning-llms/index.md
          - Building RAG Systems: blog/building-rag-systems/index.md
      - AI Applications:
          - AI for Customer Service: blog/ai-for-customer-service/index.md
          - The Future of Computer Vision: blog/future-of-computer-vision/index.md
          - Building Responsible AI Systems: blog/responsible-ai-systems/index.md
      - Categories:
          - Machine Learning: blog/category/machine-learning/index.md
          - Natural Language Processing: blog/category/nlp/index.md
          - Computer Vision: blog/category/computer-vision/index.md
          - MLOps: blog/category/mlops/index.md
  - Team: team/index.md
  - Testimonials: testimonials.md
  - Contact: contact.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Vikramardham
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/ButterflAI

copyright: Copyright &copy; 2025 ButterflAI
